
- name: Create mysql reader
  template:
    dest: "{{reader_with_source_dir}}/{{table.TABLE_NAME}}-reader.json"
    src: reader-template.json.j2
  with_items: "{{table_query_results.query_result[0]}}"
  loop_control:
    loop_var: table
  tags:
    - create-jobs