- hosts: localhost
  gather_facts: false
  vars:
    source: mysql
    table_register_sql: SELECT TABLE_NAME, CONCAT( 'SELECT * FROM ', TABLE_NAME, ' WHERE company_id = 108911;' ) `SQL`, ( SELECT CONCAT( '"`', GROUP_CONCAT( COLUMN_NAME ORDER BY ORDINAL_POSITION ASC SEPARATOR '`","`' ), '`"' ) FROM information_schema.COLUMNS c WHERE c.TABLE_SCHEMA = '{{writer_mysql_db}}' AND c.TABLE_NAME = t1.TABLE_NAME ) `COLUMNS` FROM information_schema.TABLES t1 WHERE t1.TABLE_SCHEMA = '{{writer_mysql_db}}' AND t1.TABLE_NAME IN ( SELECT TABLE_NAME FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = '{{writer_mysql_db}}' AND COLUMN_NAME = 'company_id' ) UNION ALL SELECT TABLE_NAME, CONCAT( 'SELECT * FROM ', TABLE_NAME, ';' ) `SQL`, ( SELECT CONCAT( '"`', GROUP_CONCAT( COLUMN_NAME ORDER BY ORDINAL_POSITION ASC SEPARATOR '`","`' ), '`"' ) FROM information_schema.COLUMNS c WHERE c.TABLE_SCHEMA = '{{writer_mysql_db}}' AND c.TABLE_NAME = t2.TABLE_NAME ) `COLUMNS` FROM information_schema.TABLES t2 WHERE t2.TABLE_SCHEMA = '{{writer_mysql_db}}' AND t2.TABLE_NAME NOT IN ( SELECT TABLE_NAME FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = '{{writer_mysql_db}}' AND COLUMN_NAME = 'company_id' );
    reader_mysql_host: 127.0.0.1
    reader_mysql_port: 3306
    reader_mysql_user: root
    reader_mysql_pass: myrootpass
    reader_mysql_db: udesk_proj
    writer_mysql_host: 127.0.0.1
    writer_mysql_port: 3306
    writer_mysql_user: root
    writer_mysql_pass: myrootpass
    writer_mysql_db: udesk_proj1
    exclude_tables:
      - replies
      - attachments
      - taggings
      - ticket_follows
      - customer_stats
      - customer_feeds
      - alterations
  roles:
    - common
    - mysql
    - datax

